/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "dcrpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

msg *
get_path_1(msg *argp, CLIENT *clnt)
{
	static msg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_PATH,
		(xdrproc_t) xdr_msg, (caddr_t) argp,
		(xdrproc_t) xdr_msg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

node *
sort_list_1(node *argp, CLIENT *clnt)
{
	static node clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, sort_list,
		(xdrproc_t) xdr_node, (caddr_t) argp,
		(xdrproc_t) xdr_node, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

msg *
get_echo_1(msg *argp, CLIENT *clnt)
{
	static msg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_ECHO,
		(xdrproc_t) xdr_msg, (caddr_t) argp,
		(xdrproc_t) xdr_msg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

check_node *
check_file_1(check_node *argp, CLIENT *clnt)
{
	static check_node clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, check_file,
		(xdrproc_t) xdr_check_node, (caddr_t) argp,
		(xdrproc_t) xdr_check_node, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

node *
multiplier_1(node *argp, CLIENT *clnt)
{
	static node clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, multiplier,
		(xdrproc_t) xdr_node, (caddr_t) argp,
		(xdrproc_t) xdr_node, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
