/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DCRPC_H_RPCGEN
#define _DCRPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct msg {
	char a[999];
};
typedef struct msg msg;

struct node {
	int list_data[999];
	int list_size;
};
typedef struct node node;

struct check_node {
	char fname[999];
	int res;
};
typedef struct check_node check_node;

#define ECHO_PROG 0x31111111
#define ECHO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_PATH 1
extern  msg * get_path_1(msg *, CLIENT *);
extern  msg * get_path_1_svc(msg *, struct svc_req *);
#define sort_list 2
extern  node * sort_list_1(node *, CLIENT *);
extern  node * sort_list_1_svc(node *, struct svc_req *);
#define get_ECHO 3
extern  msg * get_echo_1(msg *, CLIENT *);
extern  msg * get_echo_1_svc(msg *, struct svc_req *);
#define check_file 4
extern  check_node * check_file_1(check_node *, CLIENT *);
extern  check_node * check_file_1_svc(check_node *, struct svc_req *);
#define multiplier 5
extern  node * multiplier_1(node *, CLIENT *);
extern  node * multiplier_1_svc(node *, struct svc_req *);
extern int echo_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_PATH 1
extern  msg * get_path_1();
extern  msg * get_path_1_svc();
#define sort_list 2
extern  node * sort_list_1();
extern  node * sort_list_1_svc();
#define get_ECHO 3
extern  msg * get_echo_1();
extern  msg * get_echo_1_svc();
#define check_file 4
extern  check_node * check_file_1();
extern  check_node * check_file_1_svc();
#define multiplier 5
extern  node * multiplier_1();
extern  node * multiplier_1_svc();
extern int echo_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msg (XDR *, msg*);
extern  bool_t xdr_node (XDR *, node*);
extern  bool_t xdr_check_node (XDR *, check_node*);

#else /* K&R C */
extern bool_t xdr_msg ();
extern bool_t xdr_node ();
extern bool_t xdr_check_node ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DCRPC_H_RPCGEN */
